const form=document.querySelector('#compatibility-form'),firstInput=document.querySelector('#first-name'),secondInput=document.querySelector('#second-name'),errorMessage=document.querySelector('#error-message'),result=document.querySelector('#result');
// 한글 바르게 쓰기 필순을 기준으로 한 자모 획수표입니다. (예: ㅣ = 1획)
const strokes={initial:[2,4,2,3,6,5,4,4,8,2,4,1,3,6,4,3,4,4,3],medial:[2,3,3,4,2,3,3,4,2,4,5,3,3,2,4,5,3,3,1,2,1],final:[0,2,4,4,2,5,5,3,5,7,9,9,7,8,9,8,4,4,6,2,4,1,3,4,3,4,4,3]};
function isKoreanName(name){return /^[가-힣]{2,6}$/.test(name)}
function getNameStrokes(name){const values=[];for(const character of name){const code=character.charCodeAt(0)-0xac00,initial=Math.floor(code/588),medial=Math.floor(code%588/28),final=code%28;values.push(strokes.initial[initial]+strokes.medial[medial]+strokes.final[final])}return values}
function alternateValues(first,second){const combined=[];for(let i=0;i<Math.max(first.length,second.length);i+=1){if(first[i]!==undefined)combined.push(first[i]);if(second[i]!==undefined)combined.push(second[i])}return combined}
function reduceCompatibility(values){let current=values;while(current.length>2){const next=[];for(let i=0;i<current.length-1;i+=1)next.push((current[i]+current[i+1])%10);current=next}return current[0]*10+current[1]}
function getMessage(score){if(score===100)return['최고의 궁합, 천생연분!','말하지 않아도 통하는 완벽한 한 쌍이에요.'];if(score>=90)return['두근두근, 찰떡궁합!','서로의 매력이 자연스럽게 어우러지는 사이예요.'];if(score>=80)return['아주 좋은 궁합이에요!','함께할수록 더 빛나는 관계가 될 거예요.'];if(score>=70)return['설레는 좋은 인연이에요!','조금씩 맞춰가면 더욱 가까워질 수 있어요.'];if(score>=60)return['은근히 잘 맞는 궁합!','서로의 다른 점이 새로운 매력이 될 수 있어요.'];if(score>=50)return['노력하면 빛날 궁합!','작은 관심과 대화가 관계를 더 단단하게 해줘요.'];if(score>=40)return['서로 알아가는 중이에요!','천천히 마음을 나누면 좋은 결과가 기다려요.'];if(score>=30)return['조금 더 가까워져 볼까요?','서로를 이해하려는 마음이 가장 큰 비결이에요.'];if(score>=20)return['반전 매력이 있는 궁합!','예상 밖의 공통점을 찾아보면 재미있을 거예요.'];if(score>=11)return['아직은 낯선 궁합이에요!','가벼운 대화부터 시작해 보세요.'];if(score>=1)return['천천히 다가가 볼까요?','서두르지 말고 서로의 장점을 발견해 보세요.'];return['0%도 새로운 시작!','이름 궁합은 재미일 뿐, 마음은 직접 만들어 가는 거예요.']}
form.addEventListener('submit',event=>{event.preventDefault();const firstName=firstInput.value.trim(),secondName=secondInput.value.trim();if(!isKoreanName(firstName)||!isKoreanName(secondName)){errorMessage.textContent='두 이름 모두 한글 2~6글자로 입력해 주세요.';result.hidden=true;return}errorMessage.textContent='';const values=alternateValues(getNameStrokes(firstName),getNameStrokes(secondName)),score=reduceCompatibility(values),[title,comment]=getMessage(score);document.querySelector('#score').textContent=String(score).padStart(2,'0');document.querySelector('#result-title').textContent=title;document.querySelector('#result-comment').textContent=`${firstName}님과 ${secondName}님, ${comment}`;document.querySelector('#calculation').textContent=`획수 배열: ${values.join(' · ')} → 반복 계산 완료`;result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'nearest'})});
document.querySelector('#reset-button').addEventListener('click',()=>{result.hidden=true;form.reset();firstInput.focus()});
